# In this notebook we are going to conver fundametal concept of the tensorflow.

Topics that I going to conver :
*    Inroduction to tensors
*    Getting information from tesors
*    Manipulating tensors
*    Tensors and numpy
*    Using @tf.function (a way to speed up your python function)

### Introduction to tensors

In [1]:
# import tensorflow 
import tensorflow as tf
print(tf.__version__)

2.11.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

* Way to see documentation of any function. Ex. tf.constant()
* `print(tf.constant.__doc__)`

In [6]:
# check the number of diemension of a tensor 
scalar.ndim

0

In [7]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
# Check the dimension of the vector
vector.ndim

1

In [11]:
# Create a matrix
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [12]:
# Check the dimension of the matrix
matrix.ndim

2

In [15]:
# Create another matrix with different dtype
another_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]], dtype=tf.float32) # specity the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

* Float32 : 32 bit precision that means it's contain a number in range 10power(-38) to 10power(38) with 7 decimal places.
* High number of precision means more details or data able to store.
* Higher the precision more extact the number store in your computer.

In [16]:
 # Check the dimension of the another matrix
another_matrix.ndim

2

In [19]:
# Let's create a tensor
tensor = tf.constant(
    [
        [[1,2,3],[4,5,6]],   
        [[7,8,9],[10,11,12]],
    ]
)

In [20]:
# Check the diemention of tensor
tensor.ndim

3

What we've created so far
* Scalar : a single number
* Vector : a number with direction (e.g. wind speed and direction)
* Matrix : a 2D array of numbers
* Tensor : a nD array of numbers
* Tensor can be anything. 0D : Scalar, 1D : Vector, 2D : Matrix

### Create tensors with tf.Variable

In [25]:
# create the same tensor with tf.Varaible as above
changeable_tensor = tf.Variable([12,24])
unchangeable_tesor = tf.constant([24,36]) 
changeable_tensor, unchangeable_tesor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12, 24])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([24, 36])>)

In [26]:
# Let's try to change our changable tensor
changeable_tensor[0].assign(30)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([30, 24])>

* Variable : Update the tensor using assign method.
* constant : Not able to update once it initialized.
* Note : Rarely in practice will you need to decide whether to use `tf.constant` and `tf.Variable` to create tensors, as TensorFlow does this task for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Create random tensor

Random tensor are tensors of some arbitary size which contain random numbers.
* At beggining, TensorFlow assign weights as a random tensor.

In [31]:
# Create two random tensors but same
random_1 =  tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) 
random_2 = random_2.normal(shape=(3,2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)